name: build_and_test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: ./build_and_test
